### ISSUE TITLE
json_schema_data_formats fail when looking up 'array' 

### ISSUE THREAD

**Issue by javierabosch** [koxudaxi/datamodel-code-generator#164]
When trying to convert file data.json to model.py, I get a 
keyerror on line 171 of jsonschema.py when the type in types is 'array'. 

**To Reproduce**

Example schema:
```json

**Comment by javierabosch** [comment]
When I amended the json_schema_data_formats and added: 

 'array': {'default': Types.array}

and added Types.array: DataType(type='list'), to typ_map in types.py 

this fixed the issue. 

I am not sure if this fixes any corner cases, but I do believe json 'array' maps to a list.

**Comment by koxudaxi** [comment]
@javierabosch 
Thank you for creating this issue.

> and added Types.array: DataType(type='list'), to typ_map in types.py

This approach is not bad, However, Python `List` needs sub types like `List[str]`
The generator use a method which can parse array object to resolve subtypes of `List`.
https://github.com/koxudaxi/datamodel-code-generator/blob/01e9e58e92e44c385133b80c01caa475548929cd/datamodel_code_generator/parser/jsonschema.py#L201

I would use the method to parse your array object. I don't know why It was not used in your case.
Would you please put the json file?
I want to resolve this problem.

**Comment by javierabosch** [comment]
Hi @koxudaxi , 

The json file is quite large. Is there anyway I can email it to you? 

I saw the function you referenced in the code, but I was just monkey patching as I went along, hoping down the pipeline it would use that function.

**Comment by koxudaxi** [comment]
@javierabosch 
Thank you for your email.
I have fixed a problem which is a nested array.
I released a new version as `0.5.11`

But, I found other problems to generate models from your json data.

1. Need calling [update_forward_refs](https://pydantic-docs.helpmanual.io/usage/postponed_annotations/) for `MediaItem`  after all dependency models are defined.
I will fix the problem when I refactor a function referencing class which is related to the issue https://github.com/koxudaxi/datamodel-code-generator/issues/145
It means a feature is broken which is referencing class.

2. change types of some field to `Optional`
 the code generator uses [genson](https://pypi.org/project/genson/) to convert Json data to JSON schema. the problem happens is in `genson`. 
You should change types to `Optional`   manually after you generate models.

**Comment by koxudaxi** [comment]
@javierabosch 
> 1. Need calling update_forward_refs for MediaItem after all dependency models are defined.

Sorry, I mistake. It's no problem.

I believe this issue was resolved.  Can I close this issue?

**Comment by JosXa** [comment]
Hi, I'm on `0.5.34` and the issue still appears. I was able to track it down to the following case:

```json
{
  "my_obj": [
    {
      "items": null
    },
    {
      "items": []
    }
  ]
}
```

It doesn't matter whether the null or the [] is defined first.

The schema generated from this is:

```json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "my_obj": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "items": {
                        "type": [
                            "array",
                            "null"
                        ]
                    }
                },
                "required": [
                    "items"
                ]
            }
        }
    },
    "required": [
        "my_obj"
    ]
}
```

**Comment by JosXa** [comment]
@koxudaxi would you like me to create a fresh issue for this?

**Comment by JosXa** [comment]
My super hacky workaround:

```
def normalize_null_arrays(obj: Any):
    """ Recursively replace "null" dict values with empty lists if another item in the same list contains an empty [] """
    if isinstance(obj, dict):
        for val in obj.values():
            normalize_null_arrays(val)
        return

    if not isinstance(obj, list):
        return

    key_has_null_map = dict()
    key_has_array_map = dict()

    for i in obj:
        if not isinstance(i, dict):
            break

        for k, v in i.items():
            if v is None:
                key_has_null_map[k] = True
            if v == []:
                key_has_array_map[k] = True

    for i in obj:
        if not isinstance(i, dict):
            break

        for k, v in i.items():
            if k in key_has_array_map and k in key_has_null_map and v is None:
                i[k] = []

normalize_null_arrays(some_json_data)

```

**Comment by koxudaxi** [comment]
@JosXa
Thank you for reporting the problem.
>   would you like me to create a fresh issue for this?
Yes, please.

I will check the problem tomorrow.

**Comment by JosXa** [comment]
Alright, will do 👍
