### ISSUE TITLE
Generates duplicate model definitions from Kubernetes OpenAPI V3 input

### ISSUE THREAD

**Issue by peterth3** [koxudaxi/datamodel-code-generator#894]
**Describe the bug**
Please see https://github.com/peterth3/gybe/issues/4 for more details. Effectively, there are several duplicated models when using `datamodel-codegen` with `kubernetes`. The duplicated models cause some strange bugs where `pydantic` throws `ValidationError`s when it's expecting a different duplicated model that is used in another context.

**To Reproduce**
```sh
git clone https://github.com/peterth3/gybe.git
cd gybe
git submodule update --init --recursive
sh codegen/kubernetes.sh
```

Open `./gybe/kubernetes/io/k8s/apimachinery/pkg/api/resource.py` to see the 4 duplicates (I removed them in main, so the duplicates will be highlighted in a diff). There are a couple more mentioned in https://github.com/peterth3/gybe/issues/4 for your reference, but that is not an exhaustive list of duplicate models.

Used commandline:
```sh
datamodel-codegen --input kubernetes/api/openapi-spec/v3/ --input-file-type=openapi --output=gybe/kubernetes
```

**Expected behavior**
Models are not duplicated. Each model is unique.

**Version:**
 - OS: MacOS
 - Python version: 3.10.6
 - datamodel-code-generator version: 0.13.4

**Additional context**
Please let me know if you have any questions or there's anything I can do to help. Thanks!

**Comment by koxudaxi** [comment]
@peterth3 
I'm sorry for my late reply.
I have released a new version `0.17.0`
The version has fixed the problem.

Could you please try it?

**Comment by peterth3** [comment]
No worries @koxudaxi! I appreciate your help.

I tried again with `0.17.0` but, unfortunately, the problem still persists.

I made a [new branch](https://github.com/peterth3/gybe/tree/bug/4-duplicate-model-definitions) with a script to reproduce the issue more precisely. If you 1) clone that branch, 2) install dependencies (`pip install pytest pytest-cov datamodel-code-generator==0.17.0`), then 3) run the script (`sh codegen/test-no-duplicates`), you'll see a preview of duplicate models still being generated. 

Here's the output you'll see:

```
E       AssertionError: Found 268 duplicates:
E         	APIResourceList: 23
E         	ManagedFieldsEntry: 23
E         	ObjectMeta: 23
E         	StatusDetails: 20
E         	DeleteOptions: 20
E         	...263 more
E       assert not 268

tests/test_no_duplicates.py:26: AssertionError
```

Then you can search the `gybe/kubernetes` part of the codebase for strings like `class APIResourceList` and you'll find examples of duplicates.

<img width="329" alt="duplicates screenshot" src="https://user-images.githubusercontent.com/9690235/216266509-15a7100e-d931-4c32-aebf-fdddac82e33f.png">

I did figure out a workaround that I also included in that branch in the `gybe.clean` module that uses `ast` to remove the duplicate classes.

**Comment by koxudaxi** [comment]
@peterth3  
I have released the fix version `0.17.1`
Thank you very much!!
